export const API_REG = "http://localhost:3000/api/registro"

export const LOGIN = "/login"
export const REGISTRO = "/registro/formulario"
export const RECURSOS = "/recursos"
export const CONTACTO = "/contacto"

export const INITIAL = "http://localhost:3000/"
export const REGISTROADMIN = "/api/registro/administrador"
export const LOGINAUTHPERSONAL = "/api/auth/login-administrativo"
export const DASHSPERSONAL = "/administrativo/dashboard"
export const GETADAPTACIONES = "/api/administrativo/get-adaptaciones"
export const GETADAPTPERSONAL = "/administrativo/adaptacion/"
export const COMENTARADAP = "/api/administrativo/comentar-adaptacion/"
export const CHANGESTATE = "/api/administrativo/cambiar-estado"
export const GETCOMENTARIOS = "api/administrativo/comentarios/"
export const LOGINAUTH = "/api/auth/login-student"
export const DASHSTUDENT = "/estudiante/dashboard"
export const SOLSTUDENT = "/estudiante/solicitar-adaptacion"
export const ADAPSTUDENT = "/estudiante/adaptaciones-curriculares"
export const HERRACCESS = "/estudiante/herramientas-accesibles"
export const DOCREQUIRED = "/estudiante/documentos-necesarios"
export const SOLADAPT = "/api/estudiante/solicitar-adaptacion"
export const SOLADAPT2 = "/solicitar-adaptacion"
export const GETADAPT = "/estudiante/adaptacion/"
export const EDITADAPT = "/estudiante/editar-solicitud/"

export const LOGOUT = "/api/auth/logout"
export const TOKENJWT = 'authTokenUser'

export const APIPERSONAL = "http://localhost:3000/api/administrativo"
export const APISTUDENT = "http://localhost:3000/api/estudiante"
